server:
  port: 8082

spring:
  application:
    name: suite-auth

  datasource:
    username: user
    url: jdbc:h2:mem:persistence
    driver-class-name: org.h2.Driver
    password: pass

  h2:
    console:
      enabled: 'true'

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'

grpc:
  server:
    port: 9898

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true