server:
  port: 8082

spring:
  application:
    name: local-grpc-server

  datasource:
    username: user
    url: jdbc:h2:mem:persistence
    driverClassName: org.h2.Driver
    password: pass

  h2:
    console:
      enabled: 'true'

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'

grpc:
  server:
    port: 9898