server:
  port: 8082

spring:
  application:
    name: suite-core

  datasource:
    username: user
    url: jdbc:h2:mem:persistence
    driver-class-name: org.h2.Driver
    password: pass

  h2:
    console:
      enabled: 'true'

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'

  jackson:
    deserialization:
      fail-on-unknown-properties: 'true'

grpc:
  # This authentication was replaced for a persona way
  # auth:
  #   username: api
  #   password: api123
  client:
    auth-grpc-server:
      address: 'discovery:///suite-auth' # the server is using grpc-server-spring-boot-starter
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    audit-grpc-server:
      address: 'static://127.0.0.1:9899' # the server is using simple grpc server
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true